name: Docker

on:
  push:
    tags:
      - v*

env:
  DOCKERHUB_URL: ghcr.io/nexys-system/core/master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - name: create docker container
        run: docker build --build-arg GIT_SHA=$GITHUB_SHA --build-arg GIT_VERSION=${GITHUB_REF##*/} --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:master --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      - name: Push
        run: |
          docker push $DOCKERHUB_URL:latest
          docker push $DOCKERHUB_URL:master
          docker push $DOCKERHUB_URL:${GITHUB_REF##*/}
      - name: prep SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST" > ~/.ssh/known_hosts
      - name: deploy
        run: |
          ssh -o 'StrictHostKeyChecking no' root@${{ secrets.HOST }} << EOF
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull $DOCKERHUB_URL:master
          EOF
